site_name: アタックサーフェスマネジメント：セミナーのご案内
#site_short_name: ASMセミナーのご案内
site_description: '自分の組織のアタックサーフェスを実際に確認することで活用方法を体験。1時間半のアタックサーフェスマネジメント無料オンラインセミナーです'

theme: 
  name: material
  #name: gitbook  
  language: ja
  font: 
    text: Noto Sans JP
    code: JetBrains Mono
  features:
    - header.autohide

  #features:
   # - navigation.tabs


extra:
  generator: false
  analytics:
    provider: google
    property: G-G53Y4YRW8D

